on:
  push:
    branches: [main]
name: 🚀 Build & Deploy zelfplukken.nl
permissions:
  contents: read
  pages: write
  id-token: write
defaults:
  run:
    shell: bash
    working-directory: ./frontend

jobs:
  build:
    name: 🔨 Build application
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 8
      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - name: Install Dependencies
        run: pnpm i
      - name: Build
        run: pnpm build
        env:
          STORYBLOCK_ACCESS_TOKEN: ${{ secrets.STORYBLOCK_ACCESS_TOKEN }}
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    needs: build
    environment: prod
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4
    - name: 🔨 Build application
      uses: actions/checkout@v4
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ vars.FTP_ADDRESS }}
        username: ${{ vars.FTP_USER }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: './dist/'